Vagrant.configure("2") do |config|

  # --------------------------
  # MÁQUINA: WEB01
  # --------------------------
  config.vm.define "web01" do |db|
    db.vm.box = "ubuntu/jammy64"
    db.vm.hostname = "web01"
	config.vm.network "private_network", ip: "192.168.50.10"
	
	#PORT FORWARDING
	config.vm.network "forwarded_port", guest: 80, host: 8080, auto_correct: true
	
	
	#Provision para instalar NGINX
	config.vm.provision "shell", path: "install_nginx.sh"
	
	#Carpeta sincronizada
	config.vm.synced_folder "html", "/var/www/html"
	
	end



  # --------------------------
  # MÁQUINA: DB01
  # --------------------------
  config.vm.define "db01" do |db|
    db.vm.box = "ubuntu/jammy64"
    db.vm.hostname = "db01"
	config.vm.network "private_network", ip: "192.168.50.20"
	
	
	#Carpeta nueva - Provision
	config.vm.provision "shell", path: "datos_backup.sh"
	
	
	# CONFIGURACIÓN RECURSOS HARDWARE
	config.vm.provider "virtualbox" do |vb|
	# # Display the VirtualBox GUI when booting the machine
	# vb.gui = true
	#
	# # Customize the amount of memory on the VM:
	vb.memory = "512"
	vb.cpus = 1
	end
	end

end
