Vagrant.configure("2") do |config|

  # --------------------------
  # MÁQUINA: DB01 (MySQL)
  # --------------------------
  config.vm.define "db01" do |db|
    db.vm.box = "ubuntu/focal64"
    db.vm.hostname = "db01"
    db.vm.network "private_network", ip: "192.168.56.10"

    db.vm.provision "shell", inline: <<-SHELL
      apt-get update
      DEBIAN_FRONTEND=noninteractive apt-get install -y mariadb-server

      systemctl enable mariadb
      systemctl start mariadb

	  # Permitir conexiones desde app01
      sed -i "s/^bind-address.*/bind-address = 0.0.0.0/" /etc/mysql/mariadb.conf.d/50-server.cnf
      systemctl restart mariadb
	  
	  
      # Permitir SOLO a app01 conectarse a MySQL
      mysql -e "CREATE USER 'appuser'@'192.168.56.20' IDENTIFIED BY 'app123';"
      mysql -e "GRANT ALL PRIVILEGES ON *.* TO 'appuser'@'192.168.56.20';"
      mysql -e "FLUSH PRIVILEGES;"
	  mysql -e "CREATE DATABASE asir_db;"
	  
	  # Importar la base de datos incluida
      mysql asir_db < /vagrant/bbdd.sql
	  
    SHELL
  end
  
  # --------------------------
  # MÁQUINA: APP01 (Backend Flask)
  # --------------------------
  config.vm.define "app01" do |app|
    app.vm.box = "ubuntu/focal64"
    app.vm.hostname = "app01"
    app.vm.network "private_network", ip: "192.168.56.20"

    app.vm.provision "shell", inline: <<-SHELL
      apt-get update
      apt-get install -y python3 python3-pip

      pip3 install Flask mysql-connector-python Flask-Cors

      # Copiar API al servidor
      cp /vagrant/api_alumnos.py /home/vagrant/api_alumnos.py
      #chmod +x /home/vagrant/api_alumnos.py
	  #chown vagrant:vagrant /home/vagrant/api_alumnos.py
	  
	  # Asegurar que Flask escucha en todas las IPs
      # sed -i "s/app.run().*/app.run(host='0.0.0.0', port=5000, debug=True)/" /home/vagrant/api_alumnos.py
	  
      # Lanzar API en segundo plano
      nohup python3 /home/vagrant/api_alumnos.py &
    SHELL
  end
  
  
  # --------------------------
  # MÁQUINA: WEB01 (Nginx)
  # --------------------------
  config.vm.define "web01" do |web|
    web.vm.box = "ubuntu/focal64"
    web.vm.hostname = "web01"
    web.vm.network "private_network", ip: "192.168.56.30"

    # Port forwarding para acceso desde el host
    web.vm.network "forwarded_port", guest: 80, host: 8080

    web.vm.provision "shell", inline: <<-SHELL
      apt-get update
      apt-get install -y nginx

      # Copiar index.html como frontend
      cp /vagrant/index.html /var/www/html/index.html

      systemctl enable nginx
      systemctl restart nginx
    SHELL
  end

end
 
